alias: Shower - Reset Counters
description: "Reset session duration and water used to zero when a new shower session starts."
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.shower_active
    from: "off"
    to: "on"
conditions: []
actions:
  - action: input_number.set_value
    target:
      entity_id: input_number.shower_water_total
    data:
      value: 0
  - action: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.shower_duration
mode: single
